language: node_js

node_js:
  - 12

before_deploy:
  - rm -rf node_modules
  - zip -r nutellFrontEnd *
  - mkdir -p deploy
  - mv nutellFrontEnd.zip deploy/nutellFrontEnd.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: nutella-build
    region: ap-northeast-2
    skip_cleanup: true
    local_dir: deploy
    wait-until-deployed: true
    on:
      branch: feature/travis

before_script:
  - npm install

script:
  - CI=false npm run build

branches:
  only:
    - feature/travis

cache:
  directories:
    - node_modules
